name: Check AEP Compliance

on:
  pull_request:
    branches: [main]

jobs:
  check-aep:
    uses: dcm-project/shared-workflows/.github/workflows/check-aep.yaml@main
    with:
      additional-watch-paths: api/v1alpha1/servicetypes/**/*.yaml
